# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md
 - about.md

footer: 'checkout <a href="http://vivekkaushal.com">vivekkaushal.com</a>'

# style: light # dark (default) or light

plugins:
  - jekyll-seo-tag
